### ISSUE TITLE
How to train for multiple videos

### ISSUE THREAD

**Issue by kirbiyik** [stanleyshly/EverybodyDanceNow#3]
When I run global stage training command, the MY_TRAINING_DATASET looks for `train_facetexts128  train_img  train_label` folders. But in the official data it has 5 videos. How to train on multiple videos? Should I just put them into the same folder?

Btw, I think you've trained the model in the colab. Can you produce desired outputs? If so could you please share the checkpoint of the model which would save me from some unnecessary power consumption :)

**Comment by stanleyshly** [comment]
To train on multiple videos, stitch multiple clips together or place multiple videos in the folder, both work well. 
Yes, training in colab works well, and I have gotten go results, but I'm afraid I don't have the checkpoints anymore, I deleted them and my training dataset since they took up a lot of storage in colab.

**Comment by stanleyshly** [comment]
To train on multiple videos, stitch multiple clips together or place multiple videos in the folder, both work well. 
Yes, training in colab works well, and I have gotten go results, but I'm afraid I don't have the checkpoints anymore, I deleted them and my training dataset since they took up a lot of storage in colab.

**Comment by stanleyshly** [comment]
To train on multiple videos, stitch multiple clips together or place multiple videos in the folder, both work well. 
Yes, training in colab works well, and I have gotten go results, but I'm afraid I don't have the checkpoints anymore, I deleted them and my training dataset since they took up a lot of storage in colab.

**Comment by justinjohn0306** [comment]
> To train on multiple videos, stitch multiple clips together or place multiple videos in the folder, both work well.
> Yes, training in colab works well, and I have gotten go results, but I'm afraid I don't have the checkpoints anymore, I deleted them and my training dataset since they took up a lot of storage in colab.

can you upload your results on YT or elsewhere?

**Comment by stanleyshly** [comment]
Unfortunately, I also deleted the video files to download the folder and commit it to github.

**Comment by stanleyshly** [comment]
Issue is solved, reopen if new issues relevant the original comment come up.
